# Generated by Django 3.1.5 on 2022-06-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='location1',
            field=models.CharField(choices=[('CH', 'Corporate Headoffice'), ('OD', 'Operations Department'), ('WS', 'Work Station'), ('MD', 'Marketing Division')], max_length=50),
        ),
    ]
